project_id = "hlnfvospumcncswknqny"

[functions.save-cnh]
verify_jwt = false

[functions.update-cnh]
verify_jwt = false

[functions.delete-cnh]
verify_jwt = false

[functions.list-cnh]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.check-reseller-status]
verify_jwt = false

[functions.cleanup-expired-cnh]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.create-reseller-pix]
verify_jwt = false

[functions.remove-background]
verify_jwt = false

[functions.reseller-webhook]
verify_jwt = false

[functions.update-downloads]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.vizzionpay-webhook]
verify_jwt = false

[functions.save-rg]
verify_jwt = false
